@extends('layouts.base_profile_view')
@section('profile-content')
    <div class="col-md-12 padding-4 text-muted">Membership Certificate Information:</div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Number:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_No or "--" }} </div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Generated By:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Generated_By or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Date:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Date or "--" }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Printed:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Printed or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Print Date:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Print_Date or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Print UserID:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Print_UserID or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Collected:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Collected or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Collection Date:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Collection_Date or "--"  }}</div>
    </div>
    <div class="col-md-12 padding-4">
        <div class="col-xs-6">Certificate Collected By:</div>
        <div class="col-xs-6 text-muted">{{ $data["member_bio_data"]->Certificate_Collected_By or "--"  }}</div>
    </div>
@stop